# These are supported funding model platforms

github: construction-master
patreon: probuilder
open_collective: probuilder
ko_fi: probuilder
tidelift: probuilder
custom: https://probuilder.app/donate
