[build]
  command = "npm ci --prefix apps/client && npm run build --prefix apps/client"
  publish = "apps/client/out"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
