services:
  - type: web
    name: archtrack
    runtime: node
    plan: starter
      buildCommand: |
        npm install
      startCommand: |
        npm start
    envVars:
      - key: NODE_ENV
        value: production
        - key: MONGODB_URI
          value: mongodb://localhost:27017/archtrack
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGIN
        value: "*"
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main
