services:
  - type: web
    name: archtrack
    runtime: node
    plan: starter
    buildCommand: |
      corepack enable
      corepack prepare pnpm@latest --activate
      pnpm install --prefix apps/server
      pnpm install --prefix apps/client
      pnpm run build --prefix apps/server
      pnpm run build --prefix apps/client
    startCommand: |
      pnpm run start --prefix apps/server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Set the following in Render Dashboard → Environment
      - key: MONGODB_URI
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: CLIENT_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main
