# Alert Rules
# Construction Master App - Prometheus Alerting Rules

groups:
  - name: probuilder.rules
    rules:
      # High error rate
      - alert: HighErrorRate
        expr: rate(http_request_errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second"

      # High response time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }} seconds"

      # High memory usage
      - alert: HighMemoryUsage
        expr: memory_usage_bytes{type="used"} / memory_usage_bytes{type="total"} > 0.9
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}%"

      # High CPU usage
      - alert: HighCPUUsage
        expr: cpu_usage_percent > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%"

      # Database connection issues
      - alert: DatabaseConnectionIssues
        expr: up{job="probuilder-server"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Database connection issues"
          description: "Server is down or database is unreachable"

      # High number of failed logins
      - alert: HighFailedLogins
        expr: rate(failed_logins_total[5m]) > 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High number of failed logins"
          description: "Failed login rate is {{ $value }} per second"

      # Suspicious activity
      - alert: SuspiciousActivity
        expr: rate(suspicious_activity_total[5m]) > 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "Suspicious activity detected"
          description: "Suspicious activity rate is {{ $value }} per second"

      # Rate limit hits
      - alert: HighRateLimitHits
        expr: rate(rate_limit_hits_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High rate limit hits"
          description: "Rate limit hit rate is {{ $value }} per second"

      # Disk space low
      - alert: LowDiskSpace
        expr: (disk_usage_bytes / 1024 / 1024 / 1024) < 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space"
          description: "Disk space is {{ $value }} GB"

      # Service down
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service is down"
          description: "Service {{ $labels.job }} is down"

