apiVersion: apps/v1
kind: Deployment
metadata:
  name: probuilder-server
  namespace: probuilder
  labels:
    app: probuilder-server
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: probuilder-server
  template:
    metadata:
      labels:
        app: probuilder-server
        tier: backend
    spec:
      containers:
        - name: probuilder-server
          image: probuilder-server:latest
          ports:
            - containerPort: 3016
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: probuilder-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: probuilder-config
                  key: PORT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: probuilder-config
                  key: LOG_LEVEL
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: probuilder-secrets
                  key: MONGODB_URI
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: probuilder-secrets
                  key: REDIS_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: probuilder-secrets
                  key: JWT_SECRET
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: probuilder-secrets
                  key: SENTRY_DSN
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3016
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health/ready
              port: 3016
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: probuilder-uploads-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: probuilder-logs-pvc
      restartPolicy: Always

