blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/construction-master/probuilder/discussions
    about: Ask questions and get help from the community
  - name: Documentation
    url: https://docs.probuilder.app
    about: Check our documentation for guides and API references
